# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ToDoList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ToDoList

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'ToDoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ToDoList-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ToDoList-tvOS

  target 'ToDoList-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
